# Generated by Django 3.2.3 on 2021-06-20 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indentapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indent',
            name='balance',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='indent',
            name='paid_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='indent',
            name='product_price',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='indent',
            name='product_quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='indent',
            name='requested_amount',
            field=models.FloatField(null=True),
        ),
    ]
