# Generated by Django 3.2.4 on 2021-06-30 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indentapp', '0002_auto_20210619_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='indent',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='indentapp.profile'),
        ),
        migrations.AlterField(
            model_name='indent',
            name='balance',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='indent',
            name='paid_amount',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='indent',
            name='requested_amount',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
